
export interface VisualPinItem {
    id: string;
    emoji: string;
    name: string;
}

export const VISUAL_PIN_CATEGORIES = [
    {
        id: 'animals',
        name: 'Životinje',
        items: [
            { id: 'lion', emoji: '🦁', name: 'Lav' },
            { id: 'tiger', emoji: '🐯', name: 'Tigar' },
            { id: 'mouse', emoji: '🐭', name: 'Miš' },
            { id: 'rabbit', emoji: '🐰', name: 'Zeka' },
            { id: 'fox', emoji: '🦊', name: 'Lisica' },
            { id: 'bear', emoji: '🐻', name: 'Medved' },
            { id: 'panda', emoji: '🐼', name: 'Panda' },
            { id: 'koala', emoji: '🐨', name: 'Koala' },
            { id: 'monkey', emoji: '🐵', name: 'Majmun' },
            { id: 'cow', emoji: '🐮', name: 'Krava' },
            { id: 'pig', emoji: '🐷', name: 'Prase' },
            { id: 'frog', emoji: '🐸', name: 'Žaba' },
            { id: 'octopus', emoji: '🐙', name: 'Hobotnica' },
            { id: 'whale', emoji: '🐳', name: 'Kit' },
            { id: 'dolphin', emoji: '🐬', name: 'Delfin' },
            { id: 'fish', emoji: '🐠', name: 'Ribica' },
            { id: 'butterfly', emoji: '🦋', name: 'Leptir' },
            { id: 'bee', emoji: '🐝', name: 'Pčela' },
            { id: 'ladybug', emoji: '🐞', name: 'Bubamara' },
            { id: 'chicken', emoji: '🐔', name: 'Koka' },
            { id: 'penguin', emoji: '🐧', name: 'Pingvin' },
            { id: 'owl', emoji: '🦉', name: 'Sova' },
            { id: 'unicorn', emoji: '🦄', name: 'Jednorog' },
            { id: 'cat', emoji: '🐱', name: 'Maca' },
            { id: 'dog', emoji: '🐶', name: 'Kuca' },
            { id: 'elephant', emoji: '🐘', name: 'Slon' },
            { id: 'giraffe', emoji: '🦒', name: 'Žirafa' },
            { id: 'zebra', emoji: '🦓', name: 'Zebra' },
            { id: 'turtle', emoji: '🐢', name: 'Kornjača' },
            { id: 'crab', emoji: '🦀', name: 'Rak' },
        ]
    },
    {
        id: 'objects',
        name: 'Predmeti',
        items: [
            { id: 'phone', emoji: '📱', name: 'Telefon' },
            { id: 'ball', emoji: '⚽', name: 'Lopta' },
            { id: 'car', emoji: '🚗', name: 'Auto' },
            { id: 'gift', emoji: '🎁', name: 'Poklon' },
            { id: 'pencil', emoji: '✏️', name: 'Olovka' },
            { id: 'book', emoji: '📖', name: 'Knjiga' },
            { id: 'key', emoji: '🔑', name: 'Ključ' },
            { id: 'bell', emoji: '🔔', name: 'Zvonce' },
            { id: 'balloon', emoji: '🎈', name: 'Balon' },
            { id: 'camera', emoji: '📷', name: 'Kamera' },
            { id: 'watch', emoji: '⌚', name: 'Sat' },
            { id: 'tent', emoji: '⛺', name: 'Šator' },
            { id: 'bicycle', emoji: '🚲', name: 'Bicikl' },
            { id: 'rocket', emoji: '🚀', name: 'Raketa' },
            { id: 'airplane', emoji: '✈️', name: 'Avion' },
            { id: 'guitar', emoji: '🎸', name: 'Gitara' },
            { id: 'trumpet', emoji: '🎺', name: 'Truba' },
            { id: 'umbrella', emoji: '☂️', name: 'Kišobran' },
            { id: 'flashlight', emoji: '🔦', name: 'Lampa' },
            { id: 'hammer', emoji: '🔨', name: 'Čekić' },
            { id: 'crown', emoji: '👑', name: 'Kruna' },
            { id: 'hat', emoji: '🎩', name: 'Šešir' },
            { id: 'shoe', emoji: '👟', name: 'Patika' },
            { id: 'glasses', emoji: '🕶️', name: 'Naočare' },
            { id: 'bag', emoji: '🎒', name: 'Ranac' },
            { id: 'cup', emoji: '🏆', name: 'Pehar' },
            { id: 'diamond', emoji: '💎', name: 'Dijamant' },
            { id: 'radio', emoji: '📻', name: 'Radio' },
            { id: 'train', emoji: '🚂', name: 'Voz' },
            { id: 'bus', emoji: '🚌', name: 'Autobus' },
        ]
    },
    {
        id: 'food',
        name: 'Voće i Hrana',
        items: [
            { id: 'apple', emoji: '🍎', name: 'Jabuka' },
            { id: 'banana', emoji: '🍌', name: 'Banana' },
            { id: 'pizza', emoji: '🍕', name: 'Pica' },
            { id: 'icecream', emoji: '🍦', name: 'Sladoled' },
            { id: 'strawberry', emoji: '🍓', name: 'Jagoda' },
            { id: 'watermelon', emoji: '🍉', name: 'Lubenica' },
            { id: 'orange', emoji: '🍊', name: 'Pomorandža' },
            { id: 'grapes', emoji: '🍇', name: 'Grožđe' },
            { id: 'cherries', emoji: '🍒', name: 'Trešnje' },
            { id: 'pineapple', emoji: '🍍', name: 'Ananas' },
            { id: 'peach', emoji: '🍑', name: 'Breskva' },
            { id: 'lemon', emoji: '🍋', name: 'Limun' },
            { id: 'carrot', emoji: '🥕', name: 'Šargarepa' },
            { id: 'corn', emoji: '🌽', name: 'Kukuruz' },
            { id: 'burger', emoji: '🍔', name: 'Burgher' },
            { id: 'fries', emoji: '🍟', name: 'Krompirići' },
            { id: 'donut', emoji: '🍩', name: 'Krofna' },
            { id: 'cookie', emoji: '🍪', name: 'Keks' },
            { id: 'cake', emoji: '🍰', name: 'Torta' },
            { id: 'candy', emoji: '🍬', name: 'Bombona' },
            { id: 'lollipop', emoji: '🍭', name: 'Lizalica' },
            { id: 'chocolate', emoji: '🍫', name: 'Čokolada' },
            { id: 'popcorn', emoji: '🍿', name: 'Kokice' },
            { id: 'egg', emoji: '🥚', name: 'Jaje' },
            { id: 'cheese', emoji: '🧀', name: 'Sir' },
            { id: 'milk', emoji: '🥛', name: 'Mleko' },
            { id: 'taco', emoji: '🌮', name: 'Tako' },
            { id: 'honey', emoji: '🍯', name: 'Med' },
            { id: 'bread', emoji: '🍞', name: 'Hleb' },
            { id: 'mushroom', emoji: '🍄', name: 'Pečurka' },
        ]
    },
    {
        id: 'nature',
        name: 'Priroda i Oblici',
        items: [
            { id: 'star', emoji: '🌟', name: 'Zvezda' },
            { id: 'moon', emoji: '🌙', name: 'Mesec' },
            { id: 'sun', emoji: '☀️', name: 'Sunce' },
            { id: 'cloud', emoji: '☁️', name: 'Oblak' },
            { id: 'rainbow', emoji: '🌈', name: 'Duga' },
            { id: 'flower', emoji: '🌻', name: 'Cvet' },
            { id: 'tree', emoji: '🌳', name: 'Drvo' },
            { id: 'leaf', emoji: '🍃', name: 'List' },
            { id: 'fire', emoji: '🔥', name: 'Vatra' },
            { id: 'water', emoji: '💧', name: 'Voda' },
            { id: 'snowflake', emoji: '❄️', name: 'Pahulja' },
            { id: 'mountain', emoji: '⛰️', name: 'Planina' },
            { id: 'volcano', emoji: '🌋', name: 'Vulkan' },
            { id: 'island', emoji: '🏝️', name: 'Ostrvo' },
            { id: 'cactus', emoji: '🌵', name: 'Kaktus' },
            { id: 'rose', emoji: '🌹', name: 'Ruža' },
            { id: 'tulip', emoji: '🌷', name: 'Lala' },
            { id: 'cherryblossom', emoji: '🌸', name: 'Trešnjin cvet' },
            { id: 'evergreen', emoji: '🌲', name: 'Jelka' },
            { id: 'palm', emoji: '🌴', name: 'Palma' },
            { id: 'earth', emoji: '🌍', name: 'Zemlja' },
            { id: 'comet', emoji: '☄️', name: 'Kometa' },
            { id: 'thunder', emoji: '⚡', name: 'Grom' },
            { id: 'comet_sparkles', emoji: '✨', name: 'Sjaj' },
            { id: 'heart', emoji: '❤️', name: 'Srce' },
            { id: 'diamond_shape', emoji: '🔷', name: 'Plavi dijamant' },
            { id: 'circle', emoji: '🔴', name: 'Crveni krug' },
            { id: 'square', emoji: '🟩', name: 'Zeleni kvadrat' },
            { id: 'clover', emoji: '🍀', name: 'Detelina' },
            { id: 'shell', emoji: '🐚', name: 'Školjka' },
        ]
    }
];
